name: flutter_doki
description: "Retrive information about the device background killing apps, and
  show help to the user."
version: 1.0.1
homepage: https://zoocityboy.github.io/
documentation: https://pub.dev/documentation/flutter_doki/latest/
repository: https://github.com/zoocityboy/flutter_doki
issue_tracker: https://github.com/zoocityboy/flutter_doki/issues
topics:
  - android
  - dontkillmyapp
  - doki
platforms:
  android:
screenshots:
  - description: Dont kill my app
    path: assets/doki.png
  - description: Dont kill my app
    path: assets/flutter_01.png
environment:
  sdk: ^3.2.0
  flutter: ">=3.0.0"

dependencies:
  device_info_plus: ^11.2.1
  flutter:
    sdk: flutter
  http: ^1.2.2
  package_info_plus: ^8.2.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  plugin_platform_interface: ^2.1.8
  url_launcher_platform_interface: ^2.3.2
