name: ci

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            
          - name: Setup Flutter
            uses: subosito/flutter-action@v2
            with:
                flutter-version: '3.x'
                channel: 'stable'
                cache: true
            
          - name: Install dependencies
            run: flutter pub get

          - name: Verify formatting
            run: dart format --output=none --set-exit-if-changed .
                
          - name: Analyze project source
            run: flutter analyze

          - name: Run tests
            run: flutter test --coverage
            

          - name: Check publish warnings
            run: dart pub publish --dry-run